-- Insert Super Admin user for Bharat Agrolink
-- Email: admin@bharatagrolink.com
-- Password: bharatagrolink@2024
-- 
-- To use this file:
-- 1. Run the generate-hash.js script to get the correct hash
-- 2. Replace the hash below with the generated one
-- 3. Execute this SQL in phpMyAdmin

USE inhouse_management;

-- Delete existing admin if exists (optional - comment out if you want to keep existing)
-- DELETE FROM users WHERE email = 'admin@bharatagrolink.com';

-- Insert Super Admin
-- NOTE: Replace the hash below with the one generated by generate-hash.js script
INSERT INTO users (name, email, password, role, is_active, created_at)
VALUES (
    'Super Admin',
    'admin@bharatagrolink.com',
    '$2a$10$REPLACE_WITH_GENERATED_HASH_HERE',
    'Super Admin',
    1,
    NOW()
);

-- Verify the user was created
SELECT id, name, email, role, is_active, created_at 
FROM users 
WHERE email = 'admin@bharatagrolink.com';

